### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CodyDeeds** [eosgreen/EOS.IO-Community-Testnet-Reactivation#1]
I keep getting the below error, has anyone else gotten this yet?

Incorrect block producer key: expected EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV but got EOS55xgWhiYohaHtFTxcPMorB9MzwBfe3JgUuQEujrurmHLHiXmn

**Comment by marcinch18** [comment]
You used wrong producer key. Please ask for producer account and key in telegram group,
